package view;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Files;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import properties.LexemasAnalyzer;
import static util.Constants.Tokens;
import properties.Sintaxis;
import java_cup.runtime.Symbol;
import javax.swing.JOptionPane;
import util.Util;

public class FrmAnalizador extends javax.swing.JFrame {

    /**
     * Creates new form FrmAnalizador
     */
    public FrmAnalizador() {
        initComponents();
        setTitle("Compiler c");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        Util.clearCacheData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonAnalisis = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputCode = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAnalizarLex = new javax.swing.JTextArea();
        btnArchivo = new javax.swing.JButton();
        Borrar1 = new javax.swing.JButton();
        btnArchivo1 = new javax.swing.JButton();
        btnObject = new javax.swing.JButton();
        btnMiddleCode = new javax.swing.JButton();
        btnAssmbler = new javax.swing.JButton();
        btnBinaryCode = new javax.swing.JButton();
        btnExecute = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonAnalisis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonAnalisis.setText("Análisis Léxico");
        BotonAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnalisisActionPerformed(evt);
            }
        });

        inputCode.setColumns(20);
        inputCode.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        inputCode.setRows(5);
        jScrollPane1.setViewportView(inputCode);

        txtAnalizarLex.setColumns(20);
        txtAnalizarLex.setRows(5);
        jScrollPane2.setViewportView(txtAnalizarLex);

        btnArchivo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnArchivo.setText("Abrir Fuente");
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });

        Borrar1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Borrar1.setText("Borrar");
        Borrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Borrar1ActionPerformed(evt);
            }
        });

        btnArchivo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnArchivo1.setText("Análisis sintáctico");
        btnArchivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivo1ActionPerformed(evt);
            }
        });

        btnObject.setFont(new java.awt.Font("JetBrainsMono Nerd Font Mono", 0, 24)); // NOI18N
        btnObject.setText("Generar Objeto");
        btnObject.setEnabled(false);
        btnObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObjectActionPerformed(evt);
            }
        });

        btnMiddleCode.setFont(new java.awt.Font("JetBrainsMono Nerd Font Mono", 0, 24)); // NOI18N
        btnMiddleCode.setText("Generar Intermedio");
        btnMiddleCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiddleCodeActionPerformed(evt);
            }
        });

        btnAssmbler.setFont(new java.awt.Font("JetBrainsMono Nerd Font Mono", 0, 24)); // NOI18N
        btnAssmbler.setText("Generar Ensamblador");
        btnAssmbler.setEnabled(false);
        btnAssmbler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssmblerActionPerformed(evt);
            }
        });

        btnBinaryCode.setFont(new java.awt.Font("JetBrainsMono Nerd Font Mono", 0, 24)); // NOI18N
        btnBinaryCode.setText("Generar Ejecutable");
        btnBinaryCode.setEnabled(false);
        btnBinaryCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinaryCodeActionPerformed(evt);
            }
        });

        btnExecute.setFont(new java.awt.Font("JetBrainsMono Nerd Font Mono", 0, 24)); // NOI18N
        btnExecute.setText("Ejecutar");
        btnExecute.setEnabled(false);
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("JetBrainsMono Nerd Font Mono", 0, 24)); // NOI18N
        jLabel1.setText("Generador de archivos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonAnalisis)
                                .addGap(18, 18, 18)
                                .addComponent(btnArchivo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Borrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMiddleCode)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAssmbler)
                                .addGap(48, 48, 48)
                                .addComponent(btnObject)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btnBinaryCode)
                .addGap(123, 123, 123)
                .addComponent(btnExecute)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Borrar1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonAnalisis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnArchivo1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMiddleCode)
                    .addComponent(btnAssmbler)
                    .addComponent(btnObject))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBinaryCode)
                    .addComponent(btnExecute))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void analizarLexico() throws IOException {
        int cont = 1;

        String expr = (String) inputCode.getText();
        LexemasAnalyzer lexicos = new LexemasAnalyzer(new StringReader(expr));
        String resultado = "LINEA " + cont + "\t\tSIMBOLO\n";
        while (true) {
            Tokens token = lexicos.yylex();
            if (token == null) {
                txtAnalizarLex.setText(resultado);
                return;
            }
            switch (token) {
                case Int:
                    resultado += "  <Reservada int>\t" + lexicos.lexemas + "\n";
                    break;
                case Byte:
                    resultado += "  <Reservada byte>\t" + lexicos.lexemas + "\n";
                    break;
                case Char:
                    resultado += "  <Reservada char>\t" + lexicos.lexemas + "\n";
                    break;
                case Short:
                    resultado += "  <Reservada short>\t" + lexicos.lexemas + "\n";
                    break;
                case Long:
                    resultado += "  <Reservada long>\t" + lexicos.lexemas + "\n";
                    break;
                case Float:
                    resultado += "  <Reservada float>\t" + lexicos.lexemas + "\n";
                    break;
                case Double:
                    resultado += "  <Reservada double>\t" + lexicos.lexemas + "\n";
                    break;
                case Cadena:
                    resultado += "  <Tipo de dato>\t" + lexicos.lexemas + "\n";
                    break;
                case Linea:
                    cont++;
                    resultado += "LINEA " + cont + "\n";
                    break;
                case Comillas:
                    resultado += "  <Comillas>\t\t" + lexicos.lexemas + "\n";
                    break;
                case Include:
                    resultado += "  <Reservada include>\t" + lexicos.lexemas + "\n";
                    break;
                case Define:
                    resultado += "  <Reservada define>\t" + lexicos.lexemas + "\n";
                    break;
                case Break:
                    resultado += "  <Reservada break>\t" + lexicos.lexemas + "\n";
                    break;
                case Const:
                    resultado += "  <Reservada const>\t" + lexicos.lexemas + "\n";
                    break;
                case Continue:
                    resultado += "  <Reservada continue>\t" + lexicos.lexemas + "\n";
                    break;
                case Default:
                    resultado += "  <Reservada default>\t" + lexicos.lexemas + "\n";
                    break;
                case Register:
                    resultado += "  <Reservada register>\t" + lexicos.lexemas + "\n";
                    break;
                case Unsigned:
                    resultado += "  <Reservada unsigned>\t" + lexicos.lexemas + "\n";
                    break;
                case Struct:
                    resultado += "  <Reservada struct>\t" + lexicos.lexemas + "\n";
                    break;
                case Switch:
                    resultado += "  <Reservada switch>\t" + lexicos.lexemas + "\n";
                    break;
                case Case:
                    resultado += "  <Reservada case>\t" + lexicos.lexemas + "\n";
                    break;
                case Typedef:
                    resultado += "  <Función typedef>\t" + lexicos.lexemas + "\n";
                    break;
                case Printf:
                    resultado += "  <Función printf>\t" + lexicos.lexemas + "\n";
                    break;
                case Scanf:
                    resultado += "  <Función scanf>\t" + lexicos.lexemas + "\n";
                    break;
                case Cin:
                    resultado += "  <Función cin>\t" + lexicos.lexemas + "\n";
                    break;
                case Cout:
                    resultado += "  <Función cout>\t" + lexicos.lexemas + "\n";
                    break;
                case Using:
                    resultado += "  <Reservada using>\t" + lexicos.lexemas + "\n";
                    break;
                case Namespace:
                    resultado += "  <Reservada namespace>\t" + lexicos.lexemas + "\n";
                    break;
                case Std:
                    resultado += "  <Reservada std>\t" + lexicos.lexemas + "\n";
                    break;
                case Void:
                    resultado += "  <Reservada void>\t" + lexicos.lexemas + "\n";
                    break;
                case If:
                    resultado += "  <Reservada if>\t" + lexicos.lexemas + "\n";
                    break;
                case Else:
                    resultado += "  <Reservada else>\t" + lexicos.lexemas + "\n";
                    break;
                case Do:
                    resultado += "  <Reservada do>\t" + lexicos.lexemas + "\n";
                    break;
                case While:
                    resultado += "  <Reservada while>\t" + lexicos.lexemas + "\n";
                    break;
                case For:
                    resultado += "  <Reservada for>\t" + lexicos.lexemas + "\n";
                    break;
                case Asignation:
                    resultado += "  <Reservada asignation>\t" + lexicos.lexemas + "\n";
                    break;
                case Add:
                    resultado += "  <Reservada suma>\t" + lexicos.lexemas + "\n";
                    break;
                case Resta:
                    resultado += "  <Reservada resta>\t" + lexicos.lexemas + "\n";
                    break;
                case Times:
                    resultado += "  <Reservada multiplicación>\t" + lexicos.lexemas + "\n";
                    break;
                case Divide:
                    resultado += "  <Reservada división>\t" + lexicos.lexemas + "\n";
                    break;
                case Module:
                    resultado += "  <Reservada module>\t" + lexicos.lexemas + "\n";
                    break;
                case DoubleAnd:
                    resultado += "  <Reservada doble and>\t" + lexicos.lexemas + "\n";
                    break;
                case DoubleOr:
                    resultado += "  <Reservada doble or>\t" + lexicos.lexemas + "\n";
                    break;
                case Not:
                    resultado += "  <Reservada not>\t" + lexicos.lexemas + "\n";
                    break;
                case And:
                    resultado += "  <Reservada and>\t" + lexicos.lexemas + "\n";
                    break;
                case Or:
                    resultado += "  <Reservada or>\t" + lexicos.lexemas + "\n";
                    break;
                case GreatherThan:
                    resultado += "  <Reservada mayor que..>\t" + lexicos.lexemas + "\n";
                    break;
                case LessThan:
                    resultado += "  <Reservada menor que..>\t" + lexicos.lexemas + "\n";
                    break;
                case Equal:
                    resultado += "  <Reservada igual a..>\t" + lexicos.lexemas + "\n";
                    break;
                case NotEqual:
                    resultado += "  <Reservada distinto de..>\t" + lexicos.lexemas + "\n";
                    break;
                case GreaterEqualThan:
                    resultado += "  <Reservada mayor o igual que..>\t" + lexicos.lexemas + "\n";
                    break;
                case LessEqualThan:
                    resultado += "  <Reservada menor o igual que..>\t" + lexicos.lexemas + "\n";
                    break;
                case LeftShift:
                    resultado += "  <Reservada traslado izquierdo>\t" + lexicos.lexemas + "\n";
                    break;
                case RightShift:
                    resultado += "  <Reservada traslado derecho>\t" + lexicos.lexemas + "\n";
                    break;
                case PlusEqual:
                    resultado += "  <Reservada suma e igual>\t" + lexicos.lexemas + "\n";
                    break;
                case Increment:
                    resultado += "  <Reservada incremento>\t" + lexicos.lexemas + "\n";
                    break;
                case Decrement:
                    resultado += "  <Reservada disminución>\t" + lexicos.lexemas + "\n";
                    break;
                case MinusEqual:
                    resultado += "  <Reservada resta e igual>\t" + lexicos.lexemas + "\n";
                    break;
                case TimesEqual:
                    resultado += "  <Reservada multiplicación e igual>\t" + lexicos.lexemas + "\n";
                    break;
                case DivideEqual:
                    resultado += "  <Reservada división e igual>\t" + lexicos.lexemas + "\n";
                    break;
                case ModuleEqual:
                    resultado += "  <Reservada módulo e igual>\t" + lexicos.lexemas + "\n";
                    break;
                case True:
                    resultado += "  <Reservada True>\t" + lexicos.lexemas + "\n";
                    break;
                case False:
                    resultado += "  <Reservada False>\t" + lexicos.lexemas + "\n";
                    break;
                case Parent_a:
                    resultado += "  <Parentesis de apertura>\t" + lexicos.lexemas + "\n";
                    break;
                case Parent_c:
                    resultado += "  <Parentesis de cierre>\t" + lexicos.lexemas + "\n";
                    break;
                case Llave_a:
                    resultado += "  <Llave de apertura>\t" + lexicos.lexemas + "\n";
                    break;
                case Llave_c:
                    resultado += "  <Llave de cierre>\t" + lexicos.lexemas + "\n";
                    break;
                case Corchete_a:
                    resultado += "  <Corchete de apertura>\t" + lexicos.lexemas + "\n";
                    break;
                case Corchete_c:
                    resultado += "  <Corchete de cierre>\t" + lexicos.lexemas + "\n";
                    break;
                case Main:
                    resultado += "  <Reservada main>\t" + lexicos.lexemas + "\n";
                    break;
                case P_coma:
                    resultado += "  <Punto y coma>\t" + lexicos.lexemas + "\n";
                    break;
                case Punto:
                    resultado += "  <Punto>\t" + lexicos.lexemas + "\n";
                    break;
                case Identificador:
                    resultado += "  <Identificador>\t\t" + lexicos.lexemas + "\n";
                    break;
                case Numero:
                    resultado += "  <Numero>\t\t" + lexicos.lexemas + "\n";
                    break;
                case ERROR:
                    resultado += "  <Simbolo no definido>\n";
                    break;
                default:
                    resultado += "  < " + lexicos.lexemas + " >\n";
                    break;
            }
        }

    }

    private void BotonAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnalisisActionPerformed
        try {
            txtAnalizarLex.setForeground(Color.BLACK);
            analizarLexico();
        } catch (IOException ex) {
            Logger.getLogger(FrmAnalizador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonAnalisisActionPerformed

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        JFileChooser escoger = new JFileChooser();
        escoger.showOpenDialog(null);
        File arc = new File(escoger.getSelectedFile().getAbsolutePath());

        try {
            String ST = new String(Files.readAllBytes(arc.toPath()));
            inputCode.setText(ST);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmAnalizador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FrmAnalizador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void Borrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Borrar1ActionPerformed
        txtAnalizarLex.setText(null);
    }//GEN-LAST:event_Borrar1ActionPerformed

    private void btnArchivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivo1ActionPerformed
        String ST = inputCode.getText();
        Sintaxis s = new Sintaxis(new properties.SymbolAnalyzerCup(new StringReader(ST)));
        try {
            s.parse();
            txtAnalizarLex.setText("Analisis realizado correctamente");
            txtAnalizarLex.setForeground(new Color(25, 111, 61));
        } catch (Exception ex) {
            System.out.println(ex);
            Symbol sym = s.getS();
            txtAnalizarLex.setText("Error de sintaxis. Linea: " + (sym.right + 1) + " Columna: " + (sym.left + 1) + ", Texto: \"" + sym.value + "\"");
            txtAnalizarLex.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnArchivo1ActionPerformed

    private void btnMiddleCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiddleCodeActionPerformed
        Util.clearCacheData();
        Util.createFile(inputCode.getText());
        btnAssmbler.setEnabled(false);
        btnObject.setEnabled(false);
        btnBinaryCode.setEnabled(false);
        btnExecute.setEnabled(false);
        repaint();
        int response = Util.executeFile("intermedio");
        if (response == 0) {
            btnAssmbler.setEnabled(true);
        } else {

        }
    }//GEN-LAST:event_btnMiddleCodeActionPerformed

    private void btnObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObjectActionPerformed
        int response = Util.executeFile("objeto");
        if (response == 0) {
            btnBinaryCode.setEnabled(true);
        }
    }//GEN-LAST:event_btnObjectActionPerformed

    private void btnAssmblerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssmblerActionPerformed
        int response = Util.executeFile("ensamblador");
        if (response == 0) {
            btnObject.setEnabled(true);
        }
    }//GEN-LAST:event_btnAssmblerActionPerformed

    private void btnBinaryCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinaryCodeActionPerformed
        int response = Util.executeFile("binario");
        if (response == 0) {
            btnExecute.setEnabled(true);
        }
    }//GEN-LAST:event_btnBinaryCodeActionPerformed

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
        Util.executeFile("ejecutar");
        if (!Objects.equals(System.getProperty("os.name"), "Linux")) {
            Util.readOutput();
        };
        txtAnalizarLex.setText(Util.result);
    }//GEN-LAST:event_btnExecuteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar1;
    private javax.swing.JButton BotonAnalisis;
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnArchivo1;
    private javax.swing.JButton btnAssmbler;
    private javax.swing.JButton btnBinaryCode;
    private javax.swing.JButton btnExecute;
    private javax.swing.JButton btnMiddleCode;
    private javax.swing.JButton btnObject;
    private javax.swing.JTextArea inputCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAnalizarLex;
    // End of variables declaration//GEN-END:variables
}
