
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 29 23:52:15 COT 2022
//----------------------------------------------------

package properties;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Llave_c = 68;
  public static final int Llave_a = 67;
  public static final int Std = 30;
  public static final int Coma = 75;
  public static final int Linea = 10;
  public static final int Break = 14;
  public static final int Parent_c = 66;
  public static final int Parent_a = 65;
  public static final int Corchete_c = 70;
  public static final int Corchete_a = 69;
  public static final int True = 63;
  public static final int Long = 6;
  public static final int Punto = 74;
  public static final int Default = 17;
  public static final int Char = 4;
  public static final int GreaterEqualThan = 52;
  public static final int For = 36;
  public static final int Void = 31;
  public static final int Add = 38;
  public static final int Else = 33;
  public static final int Resta = 39;
  public static final int Int = 2;
  public static final int LessThan = 49;
  public static final int Decrement = 58;
  public static final int Cin = 26;
  public static final int LeftShift = 54;
  public static final int Using = 28;
  public static final int ERROR = 78;
  public static final int Cadena = 9;
  public static final int Typedef = 23;
  public static final int GreatherThan = 48;
  public static final int MinusEqual = 59;
  public static final int Main = 71;
  public static final int LessEqualThan = 53;
  public static final int Do = 34;
  public static final int TimesEqual = 60;
  public static final int P_coma = 72;
  public static final int Unsigned = 19;
  public static final int Short = 5;
  public static final int Times = 40;
  public static final int Scanf = 25;
  public static final int Case = 22;
  public static final int DivideEqual = 61;
  public static final int Const = 15;
  public static final int Continue = 16;
  public static final int Byte = 3;
  public static final int And = 46;
  public static final int Or = 47;
  public static final int If = 32;
  public static final int Define = 13;
  public static final int Dos_P = 73;
  public static final int EOF = 0;
  public static final int Cout = 27;
  public static final int Numero = 77;
  public static final int NotEqual = 51;
  public static final int Double = 8;
  public static final int Struct = 20;
  public static final int Namespace = 29;
  public static final int error = 1;
  public static final int False = 64;
  public static final int RightShift = 55;
  public static final int Comillas = 11;
  public static final int Float = 7;
  public static final int Increment = 57;
  public static final int Identificador = 76;
  public static final int Include = 12;
  public static final int Printf = 24;
  public static final int PlusEqual = 56;
  public static final int Divide = 41;
  public static final int Register = 18;
  public static final int Not = 45;
  public static final int Asignation = 37;
  public static final int Module = 42;
  public static final int DoubleOr = 44;
  public static final int DoubleAnd = 43;
  public static final int While = 35;
  public static final int Equal = 50;
  public static final int Switch = 21;
  public static final int ModuleEqual = 62;
}

