/* The following code was generated by JFlex 1.4.3 on 6/08/22, 5:07 p. m. */

package properties;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 6/08/22, 5:07 p. m. from the specification file
 * <tt>src/properties/LexicoCup.flex</tt>
 */
public class SymbolAnalyzerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  5,  0,  0,  3,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     3, 38,  6,  7,  0, 35, 36,  0, 41, 42, 34, 32, 50, 33, 49,  4, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 48, 47, 40, 31, 39,  0, 
     0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1, 30,  1,  1,  1,  1,  1,  1,  1, 45,  0, 46,  0,  1, 
     0, 18, 16, 10, 13, 14, 15, 23, 25,  8,  1, 19, 11, 28,  9, 20, 
    27,  1, 17, 21, 22, 12, 29, 24,  1, 26,  1, 43, 37, 44,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\21\2\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\0\1\4\1\33"+
    "\1\0\1\2\1\34\11\2\1\35\22\2\1\36\1\37"+
    "\1\40\1\0\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\0\1\3\1\0"+
    "\1\54\1\2\1\55\14\2\1\56\4\2\1\57\12\2"+
    "\3\0\1\2\1\60\2\2\1\61\1\62\1\63\5\2"+
    "\1\64\3\2\1\65\5\2\1\66\3\2\1\67\1\70"+
    "\1\2\1\3\2\0\1\2\1\71\2\2\1\72\3\2"+
    "\1\73\1\74\1\75\1\2\1\76\2\2\1\77\1\2"+
    "\1\100\2\2\2\0\3\2\1\101\1\2\1\102\1\2"+
    "\1\103\1\104\1\2\1\105\1\106\1\0\3\2\1\107"+
    "\1\2\1\110\1\111\1\2\1\112\1\113\1\114\1\115";

  private static int [] zzUnpackAction() {
    int [] result = new int[210];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\377\0\63\0\u0132"+
    "\0\u0165\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297\0\u02ca"+
    "\0\u02fd\0\u0330\0\u0363\0\u0396\0\u03c9\0\u03fc\0\u042f\0\u0462"+
    "\0\u0495\0\u04c8\0\u04fb\0\u052e\0\u0561\0\u0594\0\u05c7\0\u05fa"+
    "\0\u062d\0\u0660\0\u0693\0\u06c6\0\63\0\63\0\63\0\63"+
    "\0\63\0\63\0\63\0\63\0\63\0\u06f9\0\u072c\0\63"+
    "\0\u075f\0\u0792\0\146\0\u07c5\0\u07f8\0\u082b\0\u085e\0\u0891"+
    "\0\u08c4\0\u08f7\0\u092a\0\u095d\0\u0990\0\u09c3\0\u09f6\0\u0a29"+
    "\0\u0a5c\0\u0a8f\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e\0\u0bc1"+
    "\0\u0bf4\0\u0c27\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26\0\63"+
    "\0\63\0\63\0\u0d59\0\63\0\u0d8c\0\63\0\63\0\63"+
    "\0\63\0\63\0\63\0\63\0\63\0\63\0\u0dbf\0\u0df2"+
    "\0\u0e25\0\146\0\u0e58\0\146\0\u0e8b\0\u0ebe\0\u0ef1\0\u0f24"+
    "\0\u0f57\0\u0f8a\0\u0fbd\0\u0ff0\0\u1023\0\u1056\0\u1089\0\u10bc"+
    "\0\146\0\u10ef\0\u1122\0\u1155\0\u1188\0\146\0\u11bb\0\u11ee"+
    "\0\u1221\0\u1254\0\u1287\0\u12ba\0\u12ed\0\u1320\0\u1353\0\u1386"+
    "\0\u0d8c\0\u13b9\0\u13ec\0\u141f\0\146\0\u1452\0\u1485\0\146"+
    "\0\146\0\146\0\u14b8\0\u14eb\0\u151e\0\u1551\0\u1584\0\146"+
    "\0\u15b7\0\u15ea\0\u161d\0\146\0\u1650\0\u1683\0\u16b6\0\u16e9"+
    "\0\u171c\0\146\0\u174f\0\u1782\0\u17b5\0\146\0\146\0\u17e8"+
    "\0\63\0\u181b\0\u184e\0\u1881\0\146\0\u18b4\0\u18e7\0\146"+
    "\0\u191a\0\u194d\0\u1980\0\146\0\146\0\146\0\u19b3\0\146"+
    "\0\u19e6\0\u1a19\0\146\0\u1a4c\0\146\0\u1a7f\0\u1ab2\0\u1ae5"+
    "\0\u1b18\0\u1b4b\0\u1b7e\0\u1bb1\0\146\0\u1be4\0\146\0\u1c17"+
    "\0\146\0\146\0\u1c4a\0\146\0\146\0\u1c7d\0\u1cb0\0\u1ce3"+
    "\0\u1d16\0\146\0\u1d49\0\146\0\63\0\u1d7c\0\146\0\146"+
    "\0\146\0\146";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[210];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\5\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\3\3\1\23\1\24\1\3\1\25\2\3"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\1\55"+
    "\64\0\2\3\5\0\27\3\26\0\1\4\56\0\1\56"+
    "\4\0\1\5\1\0\1\5\61\0\1\57\32\0\1\60"+
    "\33\0\1\61\53\0\2\3\5\0\1\3\1\62\5\3"+
    "\1\63\17\3\25\0\2\3\5\0\12\3\1\64\14\3"+
    "\25\0\2\3\5\0\1\65\11\3\1\66\1\3\1\67"+
    "\4\3\1\70\5\3\25\0\2\3\5\0\14\3\1\71"+
    "\12\3\25\0\2\3\5\0\1\3\1\72\13\3\1\73"+
    "\11\3\25\0\2\3\5\0\6\3\1\74\5\3\1\75"+
    "\12\3\25\0\2\3\5\0\3\3\1\76\23\3\25\0"+
    "\2\3\5\0\3\3\1\77\6\3\1\100\1\3\1\101"+
    "\12\3\25\0\2\3\5\0\11\3\1\102\10\3\1\103"+
    "\4\3\25\0\2\3\5\0\6\3\1\104\20\3\25\0"+
    "\2\3\5\0\2\3\1\105\13\3\1\106\1\3\1\107"+
    "\1\110\5\3\25\0\2\3\5\0\11\3\1\111\10\3"+
    "\1\112\4\3\25\0\2\3\5\0\21\3\1\113\5\3"+
    "\25\0\2\3\5\0\11\3\1\114\15\3\25\0\2\3"+
    "\5\0\12\3\1\115\14\3\25\0\2\3\5\0\14\3"+
    "\1\116\12\3\25\0\2\3\5\0\16\3\1\117\10\3"+
    "\63\0\1\120\62\0\1\121\1\122\24\0\1\123\34\0"+
    "\1\124\1\0\1\125\60\0\1\126\62\0\1\127\67\0"+
    "\1\130\63\0\1\131\54\0\1\132\62\0\1\133\7\0"+
    "\1\134\52\0\1\135\10\0\1\136\53\0\1\137\23\0"+
    "\1\140\56\0\1\56\1\0\5\57\1\0\55\57\11\0"+
    "\1\141\52\0\2\3\5\0\16\3\1\142\10\3\25\0"+
    "\2\3\5\0\24\3\1\143\2\3\25\0\2\3\5\0"+
    "\1\3\1\144\25\3\25\0\2\3\5\0\15\3\1\145"+
    "\11\3\25\0\2\3\5\0\1\3\1\146\2\3\1\147"+
    "\22\3\25\0\2\3\5\0\12\3\1\150\14\3\25\0"+
    "\2\3\5\0\1\3\1\151\25\3\25\0\2\3\5\0"+
    "\15\3\1\152\11\3\25\0\2\3\5\0\1\153\26\3"+
    "\25\0\2\3\5\0\7\3\1\154\17\3\25\0\2\3"+
    "\5\0\4\3\1\155\22\3\25\0\2\3\5\0\15\3"+
    "\1\156\11\3\25\0\2\3\5\0\14\3\1\157\12\3"+
    "\25\0\2\3\5\0\3\3\1\160\23\3\25\0\2\3"+
    "\5\0\11\3\1\161\15\3\25\0\2\3\5\0\6\3"+
    "\1\162\20\3\25\0\2\3\5\0\16\3\1\163\10\3"+
    "\25\0\2\3\5\0\17\3\1\164\7\3\25\0\2\3"+
    "\5\0\12\3\1\165\14\3\25\0\2\3\5\0\5\3"+
    "\1\166\3\3\1\167\15\3\25\0\2\3\5\0\1\170"+
    "\26\3\25\0\2\3\5\0\14\3\1\171\12\3\25\0"+
    "\2\3\5\0\4\3\1\172\22\3\25\0\2\3\5\0"+
    "\23\3\1\173\3\3\25\0\2\3\5\0\1\174\26\3"+
    "\25\0\2\3\5\0\1\175\26\3\25\0\2\3\5\0"+
    "\1\176\26\3\25\0\2\3\5\0\1\177\26\3\25\0"+
    "\2\3\5\0\11\3\1\200\15\3\26\0\1\123\56\0"+
    "\1\56\3\0\1\123\36\0\1\201\23\0\1\202\62\0"+
    "\1\140\72\0\1\203\51\0\2\3\5\0\6\3\1\204"+
    "\20\3\25\0\2\3\5\0\6\3\1\205\20\3\25\0"+
    "\2\3\5\0\15\3\1\206\1\207\10\3\25\0\2\3"+
    "\5\0\16\3\1\210\10\3\25\0\2\3\5\0\11\3"+
    "\1\211\15\3\25\0\2\3\5\0\17\3\1\212\7\3"+
    "\25\0\2\3\5\0\1\213\26\3\25\0\2\3\5\0"+
    "\1\3\1\214\25\3\25\0\2\3\5\0\1\215\11\3"+
    "\1\216\14\3\25\0\2\3\5\0\10\3\1\217\16\3"+
    "\25\0\2\3\5\0\6\3\1\220\20\3\25\0\2\3"+
    "\5\0\12\3\1\221\14\3\25\0\2\3\5\0\15\3"+
    "\1\222\11\3\25\0\2\3\5\0\12\3\1\223\14\3"+
    "\25\0\2\3\5\0\6\3\1\224\20\3\25\0\2\3"+
    "\5\0\1\225\26\3\25\0\2\3\5\0\1\3\1\226"+
    "\25\3\25\0\2\3\5\0\4\3\1\227\22\3\25\0"+
    "\2\3\5\0\16\3\1\230\10\3\25\0\2\3\5\0"+
    "\11\3\1\231\15\3\25\0\2\3\5\0\6\3\1\232"+
    "\20\3\25\0\2\3\5\0\6\3\1\233\20\3\25\0"+
    "\2\3\5\0\3\3\1\234\23\3\25\0\2\3\5\0"+
    "\1\3\1\235\25\3\25\0\2\3\5\0\1\3\1\236"+
    "\25\3\25\0\2\3\5\0\5\3\1\237\21\3\25\0"+
    "\2\3\5\0\1\240\26\3\26\0\1\202\47\0\1\241"+
    "\6\0\1\242\14\0\1\243\50\0\2\3\5\0\15\3"+
    "\1\244\11\3\25\0\2\3\5\0\16\3\1\245\10\3"+
    "\25\0\2\3\5\0\1\246\26\3\25\0\2\3\5\0"+
    "\17\3\1\247\7\3\25\0\2\3\5\0\17\3\1\250"+
    "\7\3\25\0\2\3\5\0\1\3\1\251\25\3\25\0"+
    "\2\3\5\0\4\3\1\252\22\3\25\0\2\3\5\0"+
    "\3\3\1\253\23\3\25\0\2\3\5\0\16\3\1\254"+
    "\10\3\25\0\2\3\5\0\6\3\1\255\20\3\25\0"+
    "\2\3\5\0\13\3\1\256\13\3\25\0\2\3\5\0"+
    "\15\3\1\257\11\3\25\0\2\3\5\0\7\3\1\260"+
    "\17\3\25\0\2\3\5\0\2\3\1\261\24\3\25\0"+
    "\2\3\5\0\2\3\1\262\24\3\25\0\2\3\5\0"+
    "\16\3\1\263\10\3\25\0\2\3\5\0\5\3\1\264"+
    "\21\3\25\0\2\3\5\0\6\3\1\265\20\3\25\0"+
    "\2\3\5\0\16\3\1\266\10\3\25\0\2\3\5\0"+
    "\1\3\1\267\25\3\26\0\1\270\56\0\1\242\15\0"+
    "\1\271\47\0\2\3\5\0\23\3\1\272\3\3\25\0"+
    "\2\3\5\0\1\3\1\273\25\3\25\0\2\3\5\0"+
    "\1\3\1\274\25\3\25\0\2\3\5\0\6\3\1\275"+
    "\20\3\25\0\2\3\5\0\3\3\1\276\23\3\25\0"+
    "\2\3\5\0\6\3\1\277\20\3\25\0\2\3\5\0"+
    "\16\3\1\300\10\3\25\0\2\3\5\0\16\3\1\301"+
    "\10\3\25\0\2\3\5\0\21\3\1\302\5\3\25\0"+
    "\2\3\5\0\6\3\1\303\20\3\25\0\2\3\5\0"+
    "\7\3\1\304\17\3\25\0\2\3\5\0\17\3\1\305"+
    "\7\3\26\0\1\270\47\0\1\241\25\0\1\306\46\0"+
    "\2\3\5\0\12\3\1\307\14\3\25\0\2\3\5\0"+
    "\4\3\1\310\22\3\25\0\2\3\5\0\6\3\1\311"+
    "\20\3\25\0\2\3\5\0\16\3\1\312\10\3\25\0"+
    "\2\3\5\0\6\3\1\313\20\3\25\0\2\3\5\0"+
    "\7\3\1\314\17\3\42\0\1\315\45\0\2\3\5\0"+
    "\2\3\1\316\24\3\25\0\2\3\5\0\6\3\1\317"+
    "\20\3\25\0\2\3\5\0\5\3\1\320\21\3\25\0"+
    "\2\3\5\0\11\3\1\321\15\3\25\0\2\3\5\0"+
    "\6\3\1\322\20\3\24\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7599];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\35\1\11\11\1\0\1\1"+
    "\1\11\1\0\36\1\3\11\1\0\1\11\1\1\11\11"+
    "\1\0\1\1\1\0\37\1\3\0\35\1\1\11\2\0"+
    "\24\1\2\0\14\1\1\0\6\1\1\11\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[210];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public SymbolAnalyzerCup(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public SymbolAnalyzerCup(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 76: 
          { return new Symbol(sym.Register, yychar, yyline, yytext());
          }
        case 78: break;
        case 6: 
          { return new Symbol(sym.Comillas, yychar, yyline, yytext());
          }
        case 79: break;
        case 45: 
          { return new Symbol(sym.Cin, yychar, yyline, yytext());
          }
        case 80: break;
        case 38: 
          { return new Symbol(sym.DoubleOr, yychar, yyline, yytext());
          }
        case 81: break;
        case 39: 
          { return new Symbol(sym.NotEqual, yychar, yyline, yytext());
          }
        case 82: break;
        case 46: 
          { return new Symbol(sym.For, yychar, yyline, yytext());
          }
        case 83: break;
        case 16: 
          { return new Symbol(sym.LessThan, yychar, yyline, yytext());
          }
        case 84: break;
        case 65: 
          { return new Symbol(sym.Define, yychar, yyline, yytext());
          }
        case 85: break;
        case 43: 
          { return new Symbol(sym.LeftShift, yychar, yyline, yytext());
          }
        case 86: break;
        case 59: 
          { return new Symbol(sym.Float, yychar, yyline, yytext());
          }
        case 87: break;
        case 24: 
          { return new Symbol(sym.Dos_P, yychar, yyline, yytext());
          }
        case 88: break;
        case 53: 
          { return new Symbol(sym.Byte, yychar, yyline, yytext());
          }
        case 89: break;
        case 35: 
          { return new Symbol(sym.TimesEqual, yychar, yyline, yytext());
          }
        case 90: break;
        case 31: 
          { return new Symbol(sym.PlusEqual, yychar, yyline, yytext());
          }
        case 91: break;
        case 26: 
          { return new Symbol(sym.Coma, yychar, yyline, yytext());
          }
        case 92: break;
        case 71: 
          { return new Symbol(sym.Default, yychar, yyline, yytext());
          }
        case 93: break;
        case 55: 
          { return new Symbol(sym.Main, yychar, yyline, yytext());
          }
        case 94: break;
        case 19: 
          { return new Symbol(sym.Llave_a, yychar, yyline, yytext());
          }
        case 95: break;
        case 15: 
          { return new Symbol(sym.GreatherThan, yychar, yyline, yytext());
          }
        case 96: break;
        case 18: 
          { return new Symbol(sym.Parent_c, yychar, yyline, yytext());
          }
        case 97: break;
        case 61: 
          { return new Symbol(sym.Break, yychar, yyline, yytext());
          }
        case 98: break;
        case 4: 
          { /*Ignore*/
          }
        case 99: break;
        case 10: 
          { return new Symbol(sym.Times, yychar, yyline, yytext());
          }
        case 100: break;
        case 70: 
          { return new Symbol(sym.Cadena, yychar, yyline, yytext());
          }
        case 101: break;
        case 68: 
          { return new Symbol(sym.Switch, yychar, yyline, yytext());
          }
        case 102: break;
        case 23: 
          { return new Symbol(sym.P_coma, yychar, yyline, yytext());
          }
        case 103: break;
        case 74: 
          { return new Symbol(sym.Continue, yychar, yyline, yytext());
          }
        case 104: break;
        case 1: 
          { return new Symbol(sym.ERROR, yychar, yyline, yytext());
          }
        case 105: break;
        case 14: 
          { return new Symbol(sym.Not, yychar, yyline, yytext());
          }
        case 106: break;
        case 49: 
          { return new Symbol(sym.Cout, yychar, yyline, yytext());
          }
        case 107: break;
        case 77: 
          { return new Symbol(sym.Namespace, yychar, yyline, yytext());
          }
        case 108: break;
        case 13: 
          { return new Symbol(sym.Or, yychar, yyline, yytext());
          }
        case 109: break;
        case 48: 
          { return new Symbol(sym.Case, yychar, yyline, yytext());
          }
        case 110: break;
        case 2: 
          { return new Symbol(sym.Identificador, yychar, yyline, yytext());
          }
        case 111: break;
        case 22: 
          { return new Symbol(sym.Corchete_c, yychar, yyline, yytext());
          }
        case 112: break;
        case 52: 
          { return new Symbol(sym.Else, yychar, yyline, yytext());
          }
        case 113: break;
        case 44: 
          { return new Symbol(sym.Int, yychar, yyline, yytext());
          }
        case 114: break;
        case 54: 
          { return new Symbol(sym.True, yychar, yyline, yytext());
          }
        case 115: break;
        case 62: 
          { return new Symbol(sym.Scanf, yychar, yyline, yytext());
          }
        case 116: break;
        case 75: 
          { return new Symbol(sym.Unsigned, yychar, yyline, yytext());
          }
        case 117: break;
        case 32: 
          { return new Symbol(sym.Increment, yychar, yyline, yytext());
          }
        case 118: break;
        case 58: 
          { return new Symbol(sym.Using, yychar, yyline, yytext());
          }
        case 119: break;
        case 12: 
          { return new Symbol(sym.And, yychar, yyline, yytext());
          }
        case 120: break;
        case 37: 
          { return new Symbol(sym.DoubleAnd, yychar, yyline, yytext());
          }
        case 121: break;
        case 63: 
          { return new Symbol(sym.Short, yychar, yyline, yytext());
          }
        case 122: break;
        case 67: 
          { return new Symbol(sym.Struct, yychar, yyline, yytext());
          }
        case 123: break;
        case 42: 
          { return new Symbol(sym.LessEqualThan, yychar, yyline, yytext());
          }
        case 124: break;
        case 60: 
          { return new Symbol(sym.False, yychar, yyline, yytext());
          }
        case 125: break;
        case 73: 
          { return new Symbol(sym.Include, yychar, yyline, yytext());
          }
        case 126: break;
        case 28: 
          { return new Symbol(sym.If, yychar, yyline, yytext());
          }
        case 127: break;
        case 20: 
          { return new Symbol(sym.Llave_c, yychar, yyline, yytext());
          }
        case 128: break;
        case 40: 
          { return new Symbol(sym.GreaterEqualThan, yychar, yyline, yytext());
          }
        case 129: break;
        case 25: 
          { return new Symbol(sym.Punto, yychar, yyline, yytext());
          }
        case 130: break;
        case 5: 
          { return new Symbol(sym.Divide, yychar, yyline, yytext());
          }
        case 131: break;
        case 56: 
          { return new Symbol(sym.Void, yychar, yyline, yytext());
          }
        case 132: break;
        case 17: 
          { return new Symbol(sym.Parent_a, yychar, yyline, yytext());
          }
        case 133: break;
        case 7: 
          { return new Symbol(sym.Asignation, yychar, yyline, yytext());
          }
        case 134: break;
        case 66: 
          { return new Symbol(sym.Double, yychar, yyline, yytext());
          }
        case 135: break;
        case 29: 
          { return new Symbol(sym.Do, yychar, yyline, yytext());
          }
        case 136: break;
        case 27: 
          { return new Symbol(sym.DivideEqual, yychar, yyline, yytext());
          }
        case 137: break;
        case 9: 
          { return new Symbol(sym.Resta, yychar, yyline, yytext());
          }
        case 138: break;
        case 36: 
          { return new Symbol(sym.ModuleEqual, yychar, yyline, yytext());
          }
        case 139: break;
        case 47: 
          { return new Symbol(sym.Std, yychar, yyline, yytext());
          }
        case 140: break;
        case 11: 
          { return new Symbol(sym.Module, yychar, yyline, yytext());
          }
        case 141: break;
        case 57: 
          { return new Symbol(sym.Const, yychar, yyline, yytext());
          }
        case 142: break;
        case 64: 
          { return new Symbol(sym.While, yychar, yyline, yytext());
          }
        case 143: break;
        case 3: 
          { return new Symbol(sym.Numero, yychar, yyline, yytext());
          }
        case 144: break;
        case 8: 
          { return new Symbol(sym.Add, yychar, yyline, yytext());
          }
        case 145: break;
        case 33: 
          { return new Symbol(sym.MinusEqual, yychar, yyline, yytext());
          }
        case 146: break;
        case 69: 
          { return new Symbol(sym.Printf, yychar, yyline, yytext());
          }
        case 147: break;
        case 50: 
          { return new Symbol(sym.Char, yychar, yyline, yytext());
          }
        case 148: break;
        case 72: 
          { return new Symbol(sym.Typedef, yychar, yyline, yytext());
          }
        case 149: break;
        case 41: 
          { return new Symbol(sym.RightShift, yychar, yyline, yytext());
          }
        case 150: break;
        case 30: 
          { return new Symbol(sym.Equal, yychar, yyline, yytext());
          }
        case 151: break;
        case 51: 
          { return new Symbol(sym.Long, yychar, yyline, yytext());
          }
        case 152: break;
        case 21: 
          { return new Symbol(sym.Corchete_a, yychar, yyline, yytext());
          }
        case 153: break;
        case 34: 
          { return new Symbol(sym.Decrement, yychar, yyline, yytext());
          }
        case 154: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
